name: Run Python

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: 'Enter the file name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查环境
        uses: actions/checkout@v2
      - name: 配置Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: 运行Python代码
        run: |
          cd Codes
          python ${{ github.event.inputs.file_name }}
